### PR TITLE
Cont tables: added more totals

### PR DESCRIPTION
**Pull request by jonathon-love**
Closes jamovi/jamovi#779

### CODE REVIEW

**Review by raviselker — CHANGES_REQUESTED** [review]
I find the `% within $var1$` a lot more confusing then `% within row`. Took me quite a while to understand what these percentages mean with the current way of phrasing.

Screenshot from 2019-11-07 13-13-08

**Comment by jonathon-love** [comment]
so the `% within variableName` is the way that spss does it ... i feel like it's clearer ... 1-10 how strongly are you opposed to it?

**Comment by raviselker** [comment]
I'm probably a 7.5. To me, `% within $level$` (e.g., `% within OJ`) would make more sense...

**Comment by jonathon-love** [comment]
`% within $level` might be problematic in the scenario (which i don't think is too uncommon), where you have `yes`/`no` as the levels in both the row and column variable.

**Review by raviselker — APPROVED** [review]

**Pull request merged**
