### PR TITLE
descriptives XY plot 

### PR DESCRIPTION
**Pull request by victor-moreno**
HI,
This new pull request adds XY plots to descriptives when at least 2 variables are added.
The plots can show dots and/or lines, regression line (linear, quadratic, cubic, log) and loess.
Also some customization of axes are possible.

Victor

### CODE REVIEW

**Comment by jonathon-love** [comment]
i wonder if this wouldn't be a better inclusion in the `scatr` module? @raviselker ?

**Comment by raviselker** [comment]
Yeah, I need to have think about this one. It seems a bit much to add these plots to the descriptives, giving you a plot for every combination of variables. It would maybe indeed fit better in scatr (by just adding some options to the already existing scatterplot function), or maybe even the corrMatrix function.

**Comment by raviselker** [comment]
Hi Victor, I had a thought about and also took a closer look and I actually kinda like this functionality in the descriptives. I would lose a couple of the options to simplify things, and at the moment you don't add every possible combination to the results (you always just use the first variable as the x-axis variable) which feels unintuitive. What do you think @jonathon-love? Another option would indeed be to extend the scatr module: https://github.com/raviselker/scatr.

**Comment by jonathon-love** [comment]
i'm thinking we roll it into scatr, **but** we ship scatr with jamovi by default.

lots of teaching exercises require these plots, and i've just experienced this week students grappling with needing to install modules. some proportion of students don't notice the instructions that they need to install, and ask me why the menu option isn't visible, and when the modules are pre-installed, students follow the module installation instructions and wonder why they can't install it (because it's already installed).

so "why not then simply roll these analyses into jmv?" ... the issue is that these analyses we expect will be superseded when we develop a proper plot builder. at that point, we can stop shipping scatr with jamovi, but if people want the backwards compatibility, or for their old teaching materials to work, they can manually install scatr.

we're tremendously reluctant to add functionality that we'll later go on to supercede because we don't want to end up with the spss clutter situation, but i think this approach lets us have our sponge-cake and eat it too.

thoughts?

**Comment by victor-moreno** [comment]
I agree to add these plots to scatr and ship scatr which jamovi by default. This is a good option. 
I also had the experience that students don't find their way to install modules, usually because they don't read instructions.
When I have some time I will study scatr and move the code there to get a little more customizable plots.

**Comment by jonathon-love** [comment]
thanks victor, let me just get @raviselker to sign off on this.

**Comment by jonathon-love** [comment]
we also might consider renaming scatr ... to `Legacy Plots` for example.

**Comment by raviselker** [comment]
Yes, this all sounds good to me! In terms of a name change, this is also published on the CRAN at the moment under scatr, so not sure about that.

**Comment by jonathon-love** [comment]
that's a green light victor! :)

**Pull request closed without merging**
