### PR TITLE
update Chinese Simplified translation

### PR DESCRIPTION
**Pull request by mengtegroup**

### CODE REVIEW

**Comment by jonathon-love** [comment]
what do you guys think @mengtegroup, @icekylin ? is this ready to be merged do you think?

**Comment by shun2wang** [comment]
@mengtegroup ，I once disputed the translation of 'N', please reply to this.

>‘N’ can usually not be translated or written as ‘计数’ or '个案'， '例数' is only used for medical statistics but not universal.

“例数”多用在医学统计概念中，对于jamovi来说不够通用。建议修改。其余地方也有用“例数”概念，亦应译作个案/个案计数等。

I have no objection after this suggestion is resolved.

**Comment by jonathon-love** [comment]
what do you think @mengtegroup ? ... kinda hard for me to assess, but @icekylin's suggestion sounds reasonable.

cheers

**Comment by mengtegroup** [comment]
@icekylin Thank you for your advice. We have modified the translation of 'N'. We also checked the translations in the cloud version and made several changes. Please review. @jonathon-love

**Comment by jonathon-love** [comment]
sorry for the delay guys, i'll put this up soon

**Comment by jonathon-love** [comment]
OK, i've pushed the updates to:

https://cloud.jamovi.org

cheers

**Comment by mengtegroup** [comment]
@jonathon-love Thanks!!
We made a few changes after a second-round review of the cloud version. 
Please update it to the could version. It should be ready but we are happy to take a final look before you merge it.

**Comment by jonathon-love** [comment]
OK, try that

**Comment by mengtegroup** [comment]
@jonathon-love Please see the updated one. Made some minor revisions. 
It should be ready now! 
Thanks!

**Comment by jonathon-love** [comment]
sorry for the delay again ... i've updated the cloud

**Comment by jonathon-love** [comment]
what do you guys think? is this ready to be merged?

**Comment by mengtegroup** [comment]
@jonathon-love It's ready. Thanks!

**Comment by jonathon-love** [comment]
merged, thanks!

**Comment by jonathon-love** [comment]
i've added the last few strings if you want to add them. you can open a PR against master. here's the last few strings:

https://github.com/jamovi/jmv/commit/8921c89c0fad1f3784f3fa9ac2cb28176d2c6542#diff-4ccf63a789aa12ead9ec9cfdc297895c4a64e19a18e09082f19272b4f1c97276

once in, i think we'll be ready for a 2.3 release

**Comment by shun2wang** [comment]
@jonathon-love We are on holiday these days to celebrate the Chinese New Year. So we'll probably get it done as quickly as we can in the next couple of days.

Happy Chinese New Year ！ Best wishes to Jonathon,mengte's guys and the Jamovi team.

**Comment by jonathon-love** [comment]
thanks @icekylin ,

happy new year to you too!

**Pull request closed without merging**
