### PR TITLE
Added shapiro-wilk to descriptives

### PR DESCRIPTION
**Pull request by jonathon-love**

### CODE REVIEW

**Review by raviselker — COMMENTED** [review]
I wouldn't call the shapiro-wilk test "norm" as there are other normality tests as well. I would just put it under a "Normality tests" heading in the UI.

**Comment by jonathon-love** [comment]
so my plan was to have all normality tests being turned on by this (one) option ...

**Comment by raviselker** [comment]
Hmm, don't you think it's clearer if the option matches the result?

**Comment by jonathon-love** [comment]
yup, but i'm trying to prevent the options from becoming cluttered.

**Review by raviselker — APPROVED** [review]

**Pull request merged**
